title: ByzzBench
description: "ByzzBench: A Benchmark Framework for Byzantine Fault Tolerance Testing Algorithms"
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
#baseurl: "/byzzbench"
url: https://just-the-docs.github.io
repository: joaomlneto/byzzbench
#logo: icon.png
favicon_ico: favicon.ico
permalink: pretty

aux_links:
  Publication: https://drops.dagstuhl.de/entities/document/10.4230/OASIcs.FMBC.2025.13
  Repository: https://github.com/joaomlneto/byzzbench
